---

- name: NextCloud | Checking for needed config
  ansible.builtin.fail:
    msg: "The role did not get all the config needed!
    It needs: 'nextcloud' & 'nextcloud.apache.domain'"
  when: >
    nextcloud is undefined or
    (NC_CONFIG.manage.webserver and 'domain' not in NC_CONFIG.apache)

- name: NextCloud | Processing debian config
  ansible.builtin.import_tasks: debian/main.yml
  when: "ansible_distribution|lower in ['debian', 'ubuntu']"

- name: NextCloud | Displaying admin-credentials
  ansible.builtin.debug:
    msg: "Admin-User: '{{ NC_CONFIG.config.admin_user }}',
      Admin-Password: '{{ NC_CONFIG.config.admin_pwd }}'"
  when: nc_installed

- name: NextCloud | Ask User
  ansible.builtin.pause:
    prompt: 'Do you want to display the detailed setup-settings? [yes/NO]'
  register: display_prompt
  when: not no_prompts

- name: NextCloud | Displaying config
  ansible.builtin.debug:
    msg: "Data-Directory: '{{ NC_CONFIG.config.path_data }}',
      Database-Server: '{{ NC_PHP_DB_HOST }}',
      Database: '{{ NC_CONFIG.database.name }}',
      Database-User: '{{ NC_CONFIG.database.user }}',
      Database-Password: '{{ NC_CONFIG.database.pwd }}',
      Admin-User: '{{ NC_CONFIG.config.admin_user }}',
      Admin-Password: '{{ NC_CONFIG.config.admin_pwd }}'"
  when:
    - not no_prompts
    - display_prompt.user_input == 'yes'

- name: NextCloud | Cleaning up temporary password files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ tmp_pwd_file_prefix }}_nc_mysql"
    - "{{ tmp_pwd_file_prefix }}_redis"
    - "{{ tmp_pwd_file_prefix }}_nc_adm"
