---

- name: Converge
  hosts: grp_targets
  vars:
    no_prompts: true  # mariadb prompts

    nextcloud:
      enhanced_security: true
      tools: true
      php_optional: true

      manage:
        db: true
        webserver: true
        php: true
        redis: true

      php:
        srv:
          timezone: 'Europe/Vienna'
          smtp_port: 587

      config:
        path_data: '/var/test/nextcloud'

      settings:
        default_language: 'en'
        default_locale: 'de_AT'
        mail_from_address: 'testmaster@ansibleguy.net'
        mail_smtphost: 'mail.test.ansibleguy.net'

      apache:
        domain: 'nextcloud.test.ansibleguy.net'
        ip: '192.168.1.2'

      serve:
        path: '/var/www/test/nextcloud'

        ssl:
          mode: 'ca'
          cert:
            cn: 'NextCloud'
            org: 'AnsibleGuy Test'
            email: 'testmaster@ansibleguy.net'

  roles:
    - ansibleguy.sw_nextcloud
