---

- name: NextCloud | Install | Checking if NextCloud code exists
  ansible.builtin.stat:
    path: "{{ NC_CONFIG.config.path_web }}/config/config.php"
  register: nc_src_test
  tags: [upgrade]

- name: NextCloud | Install | Download
  ansible.builtin.import_tasks: install_download.yml
  when: not nc_src_test.stat.exists

- name: NextCloud | Install | Running NextCloud upgrade
  become_user: "{{ NC_HC.user }}"
  become: yes
  ansible.builtin.command: "php{{ NC_HC.php.version }} {{ NC_CONFIG.config.path_web }}/updater/updater.phar --no-interaction"
  args:
    chdir: "{{ NC_CONFIG.config.path_web }}"
  when:
    - NC_CONFIG.upgrade
    - nc_src_test.stat.exists
  tags: [upgrade]
  register: nc_installed
  changed_when: "'No update available' not in nc_installed.stdout"

# todo: fix that db pwd changes every run
- name: NextCloud | Install | Copying nextcloud config
  ansible.builtin.template:
    src: 'templates/var/www/nextcloud/config/ansible.config.php.j2'
    dest: '/var/www/nextcloud/config/ansible.config.php'
    owner: "{{ NC_HC.user }}"
    group: "{{ NC_HC.group }}"
    mode: 0750
  tags: [upgrade]
  no_log: true  # since passwords are written to the file
  changed_when: false

- name: NextCloud | Install | Updating file-ownership
  ansible.builtin.file:
    state: directory
    path: "{{ NC_CONFIG.config.path_web }}"
    owner: "{{ NC_HC.user }}"
    group: "{{ NC_HC.group }}"
    recurse: true
  changed_when: false
  tags: [upgrade]

- name: NextCloud | Install | Running NextCloud installation
  become_user: "{{ NC_HC.user }}"
  become: yes
  ansible.builtin.command: >
    php{{ NC_HC.php.version }} occ maintenance:install
    --database "{{ NC_CONFIG.database.type }}"
    --database-host "{{ NC_PHP_DB_HOST }}"
    --database-name "{{ NC_CONFIG.database.name }}"
    --database-user "{{ NC_CONFIG.database.user }}"
    --database-pass "{{ NC_CONFIG.database.pwd }}"
    --admin-user "{{ NC_CONFIG.config.admin_user }}"
    --admin-pass "{{ NC_CONFIG.config.admin_pwd }}"
    --data-dir "{{ NC_CONFIG.config.path_data }}"
  args:
    chdir: "{{ NC_CONFIG.config.path_web }}"
  changed_when: false
  when: not nc_src_test.stat.exists
  register: nc_installed
