---

- name: NextCloud | Debian | Installing dependencies
  ansible.builtin.import_tasks: install_dependencies.yml

- name: NextCloud | Debian | Configure PHP
  ansible.builtin.import_tasks: config_php.yml
  when: NC_CONFIG.manage.php
  tags: [config, php]

- name: NextCloud | Debian | Installing NextCloud
  ansible.builtin.import_tasks: install_nc.yml

- name: NextCloud | Debian | Security
  ansible.builtin.import_tasks: config_security.yml
  when: NC_CONFIG.enhanced_security
  tags: [config]

- name: NextCloud | Debian | Install | PHP | Restarting PHP-FPM
  ansible.builtin.systemd:
    name: "php{{ NC_HC.php.version }}-fpm.service"
    state: restarted
  tags: [config, php]
  changed_when: false
