---

- name: NextCloud | Debian | Config | Copying nextcloud config
  ansible.builtin.template:
    src: 'templates/var/www/nextcloud/config/ansible.config.php.j2'
    dest: '/var/www/nextcloud/config/ansible.config.php'
    owner: "{{ NC_HC.user }}"
    group: "{{ NC_HC.group }}"
    mode: 0750

- name: NextCloud | Debian | Config | Updating file-ownership
  ansible.builtin.file:
    state: directory
    path: "{{ NC_CONFIG.apache.serve.path }}"
    owner: "{{ NC_HC.user }}"
    group: "{{ NC_HC.group }}"
    recurse: true
