---

- name: NextCloud | Debian | PHP | Copying client config
  ansible.builtin.template:
    src: 'templates/etc/php/v/cli/php.ini.j2'
    dest: "/etc/php/{{ NC_HC.php.version }}/cli/php.ini"
    owner: 'root'
    group: 'root'
    mode: 0644

- name: NextCloud | Debian | PHP | Copying fpm config
  ansible.builtin.template:
    src: "templates/etc/php/v/{{ item }}.j2"
    dest: "/etc/php/{{ NC_HC.php.version }}/{{ item }}"
    owner: 'root'
    group: 'root'
    mode: 0644
  loop:
    - 'fpm/php.ini'
    - 'fpm/php-fpm.conf'
    - 'fpm/pool.d/www.conf'

- name: NextCloud | Debian | PHP | Setting custom server config
  ansible.builtin.lineinfile:
    path: "/etc/php/{{ NC_HC.php.version }}/fpm/php.ini"
    regexp: "^{{ item.key }} ="
    line: "{{ item.key }} = {{ item.value }}"
    insertbefore: '# INSERT BEFORE'
  with_dict: "{{ NC_CONFIG.php.srv }}"
  when: NC_CONFIG.php.srv | length > 0

- name: NextCloud | Debian | PHP | Setting custom FPM config
  ansible.builtin.lineinfile:
    path: "/etc/php/{{ NC_HC.php.version }}/fpm/php-fpm.conf"
    regexp: "^{{ item.key }} ="
    line: "{{ item.key }} = {{ item.value }}"
  with_dict: "{{ NC_CONFIG.php.fpm }}"
  when: NC_CONFIG.php.fpm | length > 0

- name: NextCloud | Debian | PHP | Setting custom FPM config
  ansible.builtin.lineinfile:
    path: "/etc/php/{{ NC_HC.php.version }}/fpm/pool.d/www.conf"
    regexp: "^{{ item.key }} ="
    line: "{{ item.key }} = {{ item.value }}"
  with_dict: "{{ NC_CONFIG.php.fpm_pool }}"
  when: NC_CONFIG.php.fpm_pool | length > 0

- name: NextCloud | Debian | PHP | Setting custom client config
  ansible.builtin.lineinfile:
    path: "/etc/php/{{ NC_HC.php.version }}/cli/php.ini"
    regexp: "^{{ item.key }} ="
    line: "{{ item.key }} = {{ item.value }}"
    insertbefore: '# INSERT BEFORE'
  with_dict: "{{ NC_CONFIG.php.cli }}"
  when: NC_CONFIG.php.cli | length > 0

- name: NextCloud | Debian | PHP | Copying mysql config
  ansible.builtin.template:
    src: "templates/etc/php/v/mods-available/mysql.ini.j2"
    dest: "/etc/php/{{ NC_HC.php.version }}/mods-available/mysql.ini"
    owner: 'root'
    group: 'root'
    mode: 0644

- name: NextCloud | Debian | Security | Starting/enabling PHP-FPM
  ansible.builtin.systemd:
    name: "php{{ NC_HC.php.version }}-fpm.service"
    state: restarted
    enabled: true
